server:
  port: 8081
spring:
  application:
    name: Lvtu
  profiles:
    active: dev
  datasource:
    driver-class-name: ${lvtu.datasource.driver-class-name}
    url: jdbc:mysql://${lvtu.datasource.host}:${lvtu.datasource.port}/${lvtu.datasource.database}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${lvtu.datasource.username}
    password: ${lvtu.datasource.password}
  redis:
    host: ${lvtu.redis.host}
    port: ${lvtu.redis.port}
    password: ${lvtu.redis.password}
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.Lvtu: debug

#阿里云短信配置
aliyun:
  sms:
    access-key-id: ${lvtu.sms.access-key-id}      # 从环境变量或配置中心获取
    access-key-secret: ${lvtu.sms.access-key-secret} # 从环境变量或配置中心获取
    sign-name: ${lvtu.sms.sign-name}                              # 测试阶段使用阿里云提供的测试签名
    template-code: ${lvtu.sms.template-code}                  # 测试模板CODE
    region-id: ${lvtu.alioss.endpoint}                        # 默认杭州区域